library(rvest)
library(dplyr)
link = 'https://nriol.com/india-statistics/biggest-cities-india.asp'
web=read_html(link)
Cities=web%>%html_nodes("td:nth-child(2)")%>%html_text()
View(Cities)
States=web%>%html_nodes("td:nth-child(3)")%>%html_text()
View(States)
Population=web%>%html_nodes("td:nth-child(4)")%>%html_text()
View(Population)
Language=web%>%html_nodes("td:nth-child(7) u , td:nth-child(8)")%>%html_text()
View(Language)
LargestCitiesInIndia=data.frame(Cities,States,Population)
View(LargestCitiesInIndia)
write.csv(LargestCitiesInIndia,'top 100 cities.csv')